### ISSUE TITLE
Odd display issues with the single column row block

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#104]
**Describe the bug**
I'm getting odd sizing/spacing/responsive issues on the row block with a single column. 

**To Reproduce**
1. Use the CoBlocks theme
2. Add a Row Block
3. Select one column
4. Add text
5. Any alignment (standard, wide or full) shows the issue
6. Resizing your window

**Screenshots**
Wide and fullwidth: 
![screenflow](https://user-images.githubusercontent.com/1813435/51715915-a6b1ad00-2008-11e9-93cc-7cb3c6e73492.gif)

Standard view (resizing to small)
![screenflow](https://user-images.githubusercontent.com/1813435/51715961-dc569600-2008-11e9-8dc1-436209b0c9b1.gif)

**Comment by richtabor** [comment]
It may be related to this support ticket from WordPress.org: 
https://wordpress.org/support/topic/width-of-single-column-in-row-is-constrained/

**Comment by richtabor** [comment]
It's happening on the Media Card block too. Removing the max-width (pictured-below) does the trick - though I'm not sure why it's there currently. Maybe for TwentyNineteen? 

<img width="1507" alt="screenshot 2019-01-24 20 30 09" src="https://user-images.githubusercontent.com/1813435/51719287-dff11980-2016-11e9-890c-c5ed13670167.png">

**Comment by phpbits** [comment]
@richtabor I'll make it 100% then ;)

**Comment by richtabor** [comment]
Do we need to perhaps add some styling of sorts for TwentyNineteen?

**Comment by phpbits** [comment]
@richtabor referenced the fixes I've created. I've added extra data attributes to check if block has support for alignment. If not, the width will be 100% e.g paragraph, heading.. but if block has alignment support that will be applied. Let me know your thoughts. Thanks!

**Comment by richtabor** [comment]
Check on our CoBlocks theme. ✅

**Comment by richtabor** [comment]
Looks good on 2019 too.
