### ISSUE TITLE
Custom background color for the Highlight block does not work properly 

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#107]
**Describe the bug**
Using a color palette setting is fine, but styling the Highlight block with a custom background color is styling the whole block's background — not just the <mark>

**To Reproduce**
1. Add a Highlight block
2. Add some text to it
3. Open the Color Settings panel
4. Use the color picker to set a custom background color

**Expected behavior**
The background color inline style is only applied to the <mark>

**Screenshots**
![screenflow](https://user-images.githubusercontent.com/1813435/51726162-f2c61700-2033-11e9-94d3-24da33f77312.gif)
<img width="1555" alt="screenshot 2019-01-24 23 54 01" src="https://user-images.githubusercontent.com/1813435/51726053-6ca9d080-2033-11e9-991b-2d321de2dd9e.png">

**Additional context**
It looks like the background color inline style is also getting added to the block wrapper. I'm not sure what's going on there exactly.

**Comment by phpbits** [comment]
@richtabor PR for fixes : https://github.com/thatplugincompany/coblocks/pull/109
