### ISSUE TITLE
Shape Divider should have responsive controls for changing the height of the divider

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#111]
**Is your feature request related to a problem? Please describe.**
Currently setting a height/heightAlt in a Shape Divider block - results in the divider being the same height on mobile, as well as desktop. I think it'd be a good idea to have the ability to toggle between mobile, tablet and desktop sizes (much like we do with the margin and padding controls of the Dimensions Control). 

**Describe the solution you'd like**
A control that can toggle the current BaseControl UI where users can set a height for mobile and tablet as well. When the editor window is small (viewing mobile, or tablet) the resizableBox handles should turn off — as the styles from within the mobile and tablet BaseControls should take affect. 

**Block Sidebar Control UI**
![150](https://user-images.githubusercontent.com/1813435/51752355-4a40a300-2085-11e9-9097-56bbefe8e9d5.png)

**Currently occurs (if there is no mobile height)**
<img width="615" alt="screenshot 2019-01-25 09 35 47" src="https://user-images.githubusercontent.com/1813435/51752169-cc7c9780-2084-11e9-8d94-618c2866176a.png">

**Comment by richtabor** [comment]
It's be awesome if users could resize the resizableBox components when the viewport is mobile or tablet, and those values are saved as mobile and tablet heights! I'm not sure if that's possible though. 🤔

**Comment by richtabor** [comment]
> @richtabor we can add the option but users have to resize the browser in order to get the preview, I think.
> 
> Gutenberg team is still working on the devices preview, so we have to wait for that. What do you think?

Yea that's fine. Basically the same behavior as our dimensions control - right?

**Comment by richtabor** [comment]
> and oh! Not sure if we can have the values changed based on viewport but I can definitely try ;)

That would be super cool really! Idk what I think about it, but maybe we have three resizable boxes, where each is visible only in its relative viewport? Or something like that?

**Comment by spencerfinnell** [comment]
@richtabor I made a plugin that assigns a class to `.editor-styles-wrapper` based on the selected page template: https://github.com/bigboxwc/wp-editor-page-template-class

You could use something like that to add a class to the wrapper based on a selected viewport size, and adjust `.wp-block` width and other controls based on that.

**Comment by richtabor** [comment]
> @richtabor I made a plugin that assigns a class to `.editor-styles-wrapper` based on the selected page template: https://github.com/bigboxwc/wp-editor-page-template-class
> 
> You could use something like that to add a class to the wrapper based on a selected viewport size, and adjust `.wp-block` width and other controls based on that.

Interesting @spencerfinnell - thanks for the pointer! 💪

**Comment by phpbits** [comment]
@richtabor Finally figured it out 🎉🎉🎉🎉🎉

https://phpbits.d.pr/7dd1ET

**Comment by richtabor** [comment]
Awesome! Works great!
