### ISSUE TITLE
Provide Upgrade Path/Deprecation Support for Block Colors

### ISSUE THREAD

**Issue by spencerfinnell** [thatplugincompany/coblocks#12]
I haven't checked the other blocks, but updating Coblocks 1.1.1 to 1.1.3 breaks existing Alerts.

1.1.1

<img width="745" alt="screen shot 2018-08-14 at 12 17 16 pm" src="https://user-images.githubusercontent.com/491124/44104204-4203eaca-9fbc-11e8-986e-f794bba78e4e.png">

1.1.3

<img width="733" alt="screen shot 2018-08-14 at 12 17 38 pm" src="https://user-images.githubusercontent.com/491124/44104219-48d11efe-9fbc-11e8-9911-0c6e0712c049.png">

This is because the block was originally saved with a custom style (for the custom colors) and now uses the class names.

```
index.js?ver=1534256213:2 Block validation: Block validation failed for `coblocks/alert` (Object).

Expected:

<div class="wp-block-coblocks-alert is-default-alert aligncenter has-background has-2571-d-4-background-color has-2571-d-4-border-color"><p class="wp-block-coblocks-alert__title has-text-color has-ffffff-color">[object Object]</p></div>

Actual:

<div class="wp-block-coblocks-alert aligncenter" style="background-color:#2571d4;border-color:#2571d4;text-align:center"><div class="wp-block-coblocks-alert__title"><p style="color:#ffffff"><strong>This is an alert title</strong></p></div><p class="wp-block-coblocks-alert__text" style="color:#ffffff">This is an alert description.</p></div>
```

You can see how the core Button block migrates old hex `style` attributes to new classes here: https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/button/index.js#L127

**Comment by richtabor** [comment]
Thanks @spencerfinnell — good catch. 👍

**Comment by richtabor** [comment]
Closing as it's really out of date now. 👍
