### ISSUE TITLE
Click to Tweet block toolbar display issues

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#128]
It's relative to the username input field. Will likely just need a few minor touchups to the styling. The top toolbar looks fine, but we need to confirm it when we push a fix for this. 

**Screenshots**
<img width="618" alt="screenshot 2019-01-25 13 32 14" src="https://user-images.githubusercontent.com/1813435/51765425-aca99b80-20a5-11e9-848e-ddac24a0431b.png">

**Comment by phpbits** [comment]
@richtabor Added fixes on `toolbar-fields-styling` branch. Not sure about the styling when selected though. Would you mind adding that? Thanks!

**Comment by richtabor** [comment]
I’ll take a look. Do you think we should just move it to the inspector?

**Comment by phpbits** [comment]
> I’ll take a look. Do you think we should just move it to the inspector?

I think it's better to have that on toolbar. easier to access that the inspector. Also it's more noticeable.

**Comment by richtabor** [comment]
Ok, I'll see what I can do

**Comment by richtabor** [comment]
<img width="599" alt="screenshot 2019-01-28 08 03 32" src="https://user-images.githubusercontent.com/1813435/51838061-430ed480-22d3-11e9-8ec4-4c415e830dae.png">
