### ISSUE TITLE
Follow button isn't working on Author block

### ISSUE THREAD

**Issue by mahdiyazdani** [thatplugincompany/coblocks#13]
It seems clicking on the "Follow" button is causing an issue which prevents the block from being previewed.

![](https://media.giphy.com/media/7OWP2TWYGFf5FLcVGP/giphy.gif)

Also, I have noticed the inspector controls are [commented out](https://github.com/thatplugincompany/coblocks/blob/master/src/blocks/author/components/edit.js#L6) within the source code of the block.

**Comment by richtabor** [comment]
Thanks for the gif @mahdiyazdani — that's super helpful. I'll take a look at it. 

Yea, there are not any Inspector Controls just yet.
