### ISSUE TITLE
Enhance the inserter modal pop-up entry

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#137]
The loading animation that's applied to the modal by core Gutenberg is not quite attractive and pretty shaky. I think it'd be better to remove it altogether for now. Maybe we'll go back in and tweak it later, but it's not working as is. 

Current: 
![screenflow](https://user-images.githubusercontent.com/1813435/51768504-80dee380-20ae-11e9-8605-19d5038b393f.gif)

New: 
![screenflow](https://user-images.githubusercontent.com/1813435/51768596-c00d3480-20ae-11e9-87ca-90e49ece6219.gif)

## Todo
1. Override the `.components-modal__screen-overlay` animation (as pictured below) 
<img width="477" alt="screenshot 2019-01-25 14 33 09" src="https://user-images.githubusercontent.com/1813435/51768384-26458780-20ae-11e9-80f6-d78c7c888c32.png">

2. Override the `.components-modal__frame` animation (as pictured below) 
<img width="523" alt="screenshot 2019-01-25 14 33 55" src="https://user-images.githubusercontent.com/1813435/51768416-407f6580-20ae-11e9-8e07-ed573bd78959.png">

3. Set a proper min-height for the `.components-modal__frame.blockcoblocks-modal-component .components-tab-panel__tab-content` div. 310px seems to work on I think.

**Comment by richtabor** [comment]
If we want a subtle fade-in (which I'm not opposed to), we could leave the `edit-post__fade-in-animation` animation on the `.components-modal__screen-overlay` element. 
![screenflow](https://user-images.githubusercontent.com/1813435/51768886-8e489d80-20af-11e9-98b2-a5cc9968badb.gif)

**Comment by phpbits** [comment]
@richtabor removed the animation for `.components-modal__frame` . There's no option to add custom class for `.components-modal__screen-overlay`, I don't think removing the animation fill globally is a good idea. What do you think? Thanks!

**Comment by richtabor** [comment]
Ah makes sense. I'll give it a look.

**Comment by richtabor** [comment]
Looks great!
