### ISSUE TITLE
'Alert Type' doesn't do anything if color settings have previously been changed.

### ISSUE THREAD

**Issue by DannyCooper** [thatplugincompany/coblocks#14]
![2018-08-24 11 11 28](https://user-images.githubusercontent.com/152804/44579524-91510200-a78e-11e8-8510-08a13659b1ab.gif)

This may be intentional to ensure user settings aren't lost, but it's not obvious from the implementation.

**Comment by richtabor** [comment]
Hey @DannyCooper, do you have custom colors applied already as well?

**Comment by richtabor** [comment]
I just tested and I think that's what's going on.

**Comment by DannyCooper** [comment]
Hey Rich,

Sorry, I don't think my initial comment was clear. I did previously choose custom colors. So I understand the setting might not do anything (to protect my custom color choices). However, that's not obvious from the UI. How about hiding that setting when a custom color is set? I think that's possible.

**Comment by richtabor** [comment]
@DannyCooper I'm thinking I may have the alert type selected there override/reset custom colors.

**Comment by richtabor** [comment]
Now when you select custom colors, then go back and set the alert type, it'll override your custom colors to use the alert type colors instead (as a user decided to do so).
