### ISSUE TITLE
We should switch the inner and wrapper divs for the Media Card block

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#141]
In all our other blocks, we have the main `block` > ` __inner` block inside as the first child. We should swap the `.wp-block-coblocks-media-card__inner` and `.wp-block-coblocks-media-card__wrapper` div names so that the Media Block follows that same structure. 

We'll need to make sure the appropriate styles for each are correct as well.

**Comment by phpbits** [comment]
@richtabor Sorry was using the wrong branch, accidentally merged to master. It's working fine though. Let me know how it goes. Thanks!

**Comment by richtabor** [comment]
Yup, looks good!
