### ISSUE TITLE
Styles may be too specific in the Media Card block

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#142]
[These styles](https://github.com/thatplugincompany/coblocks/blob/master/src/blocks/media-card/styles/style.scss#L129-L145) within the Media Card style.scss stylesheet are too specific. Some themes may not have an `.entry` div wrapper. 

Is is ok to move them [here](https://github.com/thatplugincompany/coblocks/blob/master/src/blocks/media-card/styles/style.scss#L62-L75)? Just the p and headings.

**Comment by phpbits** [comment]
@richtabor how about not using classes and just use `div div`. Just to make sure it'll override other theme's styling. What do you think?

**Comment by richtabor** [comment]
Even div > div may be too specific. I’m just thinking we don’t have much control of the markup outside of the block. So it may be best to try and keep our styling logic as localized as possible.

**Comment by phpbits** [comment]
@richtabor I'll check with 2019 theme if that will work. Using `important` isn't an option so having multiple level is the only one that works right now.

**Comment by richtabor** [comment]
Well we have the is-twentynineteen body class added right? We can add specific styling to override that conflict with just that theme.

**Comment by richtabor** [comment]
We can have super specific styling, for the TwentyNineteen theme - but I’m saying we can’t have that same styling as the fallback for everything else (as it’s too specific)

**Comment by phpbits** [comment]
@richtabor ah! I've referenced the fixes :)
