### ISSUE TITLE
The .has-custom-font class should be available within the editor 

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#150]
To make it easier for themes to interface with the typography controls, we should have this class available within the editor’s blocks. That way, when the custom font is applied, they won’t accidentally override. 

For example, theme’s editor stylesheet would use `.wp-block-heading:not(.is-custom-font) {}` if there was a conflict on their end with fonts.

**Comment by phpbits** [comment]
@richtabor this is available on the editor via `data` attribute. Here's the reference : https://github.com/thatplugincompany/coblocks/blob/c24fd3bfcc4fb25f1d7c3adcd5fe28a9ff50b3d7/src/extensions/typography/styles/editor.scss#L31 . Thanks!

**Comment by richtabor** [comment]
I saw that. I suppose that will be fine then. :)
