### ISSUE TITLE
Add <code> inline editor format

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#152]
Much like how our uppercase formatting toolbar control is available, it would be neat if folks can also use <code> inline.

**Comment by phpbits** [comment]
@richtabor tested and really nice! Working perfectly. Makes me think if we can do colors too :D

**Comment by richtabor** [comment]
> @richtabor tested and really nice! Working perfectly. Makes me think if we can do colors too :D

We can! I have [an idea card](https://trello.com/c/VkdvocfY) on our Trello board for potentially implementing something like that in the near future. 🚀
