### ISSUE TITLE
Add checkbox style to core List block

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#154]
I imagine this would be pretty easy to implement. I'll explore it a bit and see what I come up with. If it works, we could possibly extend other core blocks rather easily (making CoBlocks even more useful).

**Comment by richtabor** [comment]
Yup! Not too shabby. 

<img width="692" alt="screenshot 2019-01-27 14 10 40" src="https://user-images.githubusercontent.com/1813435/51805594-5707f700-223d-11e9-84e1-379037a5cfa5.png">

**Comment by phpbits** [comment]
@richtabor wow! That's awesome! Pretty neat solution for checklists :)
