### ISSUE TITLE
PHP warning returning on 404

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#156]
**Describe the bug**
Theres a PHP warning returning on the 404 page. 

**To Reproduce**
1. Activate the CoBlocks theme (but likely any theme)
2. Ensure WP_DEBUG is on.
3. Navigate to a random page to view the 404 page.

**Expected behavior**
No error!👌

**Screenshots**
<img width="1343" alt="screen shot 2019-01-27 at 2 04 17 pm" src="https://user-images.githubusercontent.com/1813435/51806225-7145d300-2245-11e9-85d2-3fa81f08bf53.png">

**Comment by phpbits** [comment]
@richtabor created a PR : https://github.com/thatplugincompany/coblocks/pull/158
