### ISSUE TITLE
What if we had a "Add CoBlocks Section" button to open the inserter modal

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#157]
Kind of like how Elementor does, but it opens our modal instead. Just a though. What do you think @phpbits?

**Comment by phpbits** [comment]
@richtabor That'll be good, not sure if we can auto open modal though but I can try :)

**Comment by richtabor** [comment]
Let's move this potentially to 2.1. I think it'd be nice, but not super important for 2.0.

**Comment by richtabor** [comment]
> @richtabor Good idea, checked it out already actually and seems "hack" are needed in order to make this work. Using `document` and insert the button then add custom onClick function. Not via Gutenberg way though since there's no filter available for the top component.

Alrighty, yea - let's think about this later. 💪
