### ISSUE TITLE
Pricing Table Block, 3 tables with no alignment set

### ISSUE THREAD

**Issue by seb86** [thatplugincompany/coblocks#16]
Editing 3 tables with no alignment does not match the front-end. It's squashed. In fact the width of each table are not even but that may be because each table has different content.

On the front-end, you have the first 2 tables even and the third table on a second row in full width which I do not mind but the editing experience for this particular setting needs a adjusting.

**Comment by richtabor** [comment]
Hi @seb86. I've pushed the update to resolve this a bit ago. Here's what it should look like now: 

<img width="1060" alt="screenshot 2018-11-29 16 20 08" src="https://user-images.githubusercontent.com/1813435/49252661-a8893680-f3f2-11e8-9d80-1cfd4922077c.png">
