### ISSUE TITLE
Improve responsive nature of Media Card

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#160]
It's ok right now, but it really could be much better. I'm thinking we should maybe make the breakpoint where it switching to stacked a bit higher.

**Comment by phpbits** [comment]
@richtabor what breakpoint do you have in mind?

**Comment by richtabor** [comment]
I think we just need to fix TwentyNineteen, since it adds a lot of left/right space on mid-range views. I'll take this one and adjust it

**Comment by richtabor** [comment]
Ok, if we could do 800px (only on TwentyNineteen) that would work! @phpbits Want to take it from here?

**Comment by phpbits** [comment]
@richtabor referenced the branch with fixes. Thanks!
