### ISSUE TITLE
Add backgroundColor support to Feature Block

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#169]
The parent Features block has support, but we still need to add it to each individual Feature block inside of it.

**Comment by richtabor** [comment]
Actually, I don't think this is a good idea. It would make the block quite a bit more complex.

**Comment by richtabor** [comment]
Actually, I think this could work ok.

**Comment by richtabor** [comment]
<img width="861" alt="screenshot 2019-02-01 07 53 30" src="https://user-images.githubusercontent.com/1813435/52124202-79f82980-25f6-11e9-9332-636a85e2566d.png">

**Comment by richtabor** [comment]
@phpbits I added all the bits here, we just need to hook in the padding dimensionsControl.

**Comment by phpbits** [comment]
@richtabor Added :)
