### ISSUE TITLE
Remove additional left/right padding on the Features block

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#173]
**Describe the bug**
Extra padding is being added to the features block

**To Reproduce**
1. Add a Features Block
2. Set the block to wide alignment
3. Press Publish

**Expected behavior**

**Screenshots**
<img width="1295" alt="screenshot 2019-01-29 09 22 26" src="https://user-images.githubusercontent.com/1813435/51914694-6dca5d00-23a7-11e9-842f-641807fb5e05.png">

**Additional context**

**Comment by phpbits** [comment]
@richtabor Removed 👍
