### ISSUE TITLE
Features block gutters do not work entirely

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#174]
**Describe the bug**
First, the small, medium, large and huge options don't make much of a difference. And second, they don't seem to be working entirely. Also, the huge option is smaller than large. 

The first feature column should never have margin/gutter applied to it's left. And the last column should not have any applied to it's right. 

**Editor Gif:**
![screenflow](https://user-images.githubusercontent.com/1813435/51915196-7e2f0780-23a8-11e9-98d2-352d8e608c25.gif)

**Comment by richtabor** [comment]
We need to make sure the frontend styling is the same as well for the gutters.

**Comment by phpbits** [comment]
@richtabor Fixed 👍

**Comment by richtabor** [comment]
We're close! The gutters should also translate as margin bottom on mobile (the same as the Row block does as of 1.8). 

Here's a screen recording of the front-end with two features in each block - with each gutter option applied. I styled them so we could see the actual feature containers. 

![screenflow](https://user-images.githubusercontent.com/1813435/52121753-af991480-25ee-11e9-88f7-79503a7a2ac0.gif)

**Comment by phpbits** [comment]
@richtabor fixed :)
