### ISSUE TITLE
Remove the 'style' block attribute, if we're not using it

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#177]
@phpbits, just wanted to check and see we need the `style` attribute ([code link](https://github.com/thatplugincompany/coblocks/blob/icons-block/src/blocks/icon/index.js#L54-L56)) within the Icon Block.

**Comment by phpbits** [comment]
@richtabor right! I'll remove that! Got an issue with styles before since it's cannot be accessed on index.js. Fixed it though :) I'll remove it.
