### ISSUE TITLE
If "No bottom spacing" is enabled, the next block automatically have its "No top spacing" toggled

### ISSUE THREAD

**Issue by phpbits** [thatplugincompany/coblocks#192]
Basically where you would not have to toggle it, go to the next button, open advanced settings, and toggle that block as well.

**Comment by richtabor** [comment]
@phpbits I'm still getting the space there, or am I missing something? Here's a recording:
![screenflow](https://user-images.githubusercontent.com/1813435/52129514-b54e2480-2605-11e9-8d49-36a22f4c454e.gif)

**Comment by phpbits** [comment]
@richtabor Ah! I've added that to `onChange`. Let me check if I can do that on block insert ;)
