### ISSUE TITLE
Add URL field to be able to link Icon Block

### ISSUE THREAD

**Issue by phpbits** [thatplugincompany/coblocks#193]
Make the icon linkable. Add the link field to inspector control.

**Comment by phpbits** [comment]
@richtabor do you think this link is better than wrapping the SVG? Thanks!

**Comment by richtabor** [comment]
@phpbits I don't think I do, but is there a benefit of doing it in this method?

**Comment by phpbits** [comment]
@richtabor SVG styling inside links probably. I can change it though, what do you think?

**Comment by richtabor** [comment]
Also, let's move the Icon Link setting and Open to New Window into a separate PanelBody (titled Link Settings), just like how the core Image block does. 

We don't need the "Link To" option first though. 
<img width="292" alt="screenshot 2019-02-01 09 31 54" src="https://user-images.githubusercontent.com/1813435/52128923-3ad0d500-2604-11e9-9d02-41c48e195fb4.png">

**Comment by richtabor** [comment]
And rename "Open to New Window" to Open in New Tab (like the Image block).

**Comment by richtabor** [comment]
> @richtabor SVG styling inside links probably. I can change it though, what do you think?

I say we wrap it in the <a> like normal.

**Comment by richtabor** [comment]
> Also, let's move the Icon Link setting and Open to New Window into a separate PanelBody (titled Link Settings), just like how the core Image block does.
> 
> We don't need the "Link To" option first though.
> <img alt="screenshot 2019-02-01 09 31 54" width="292" src="https://user-images.githubusercontent.com/1813435/52128923-3ad0d500-2604-11e9-9d02-41c48e195fb4.png">

We don't need the Link CSS Class (not sure how useful that is really, esp in this context), but the Link Rel would be nice.
