### ISSUE TITLE
Image Overlay on Feature block is positioning on top of the content

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#198]
**Describe the bug**
Applying an image overlay to a Feature block has the overlay applied on top of the content, instead of below its, on the frontend of the site.

**To Reproduce**
1. Add a Features block
2. Add a background image
3. Choose a background color
4. Set the overlay opacity
5. See error

**Expected behavior**
Perform as it does within the editor, where the overlay is under the text.

**Screenshots**
![screenflow](https://user-images.githubusercontent.com/1813435/52126574-af544580-25fd-11e9-8200-417267c9062e.gif)

**Comment by phpbits** [comment]
@richtabor Can you push the changes? I think position relative will fix this issue on the frontend ;)

**Comment by phpbits** [comment]
@richtabor Pushed the fixes :) Thanks
