### ISSUE TITLE
Replace the "CoBlocks" heading in the modal with our icon

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#217]
The bit above "My Sections":

<img width="489" alt="screenshot 2019-02-04 12 08 12" src="https://user-images.githubusercontent.com/1813435/52224285-9d7cd780-2875-11e9-968d-c6b13f375185.png">

**Comment by phpbits** [comment]
@richtabor Added with Layouts heading 👍

**Comment by phpbits** [comment]
<img width="1036" alt="screen shot 2019-02-05 at 1 13 48 am" src="https://user-images.githubusercontent.com/3365507/52225790-34817800-28e6-11e9-9880-bf82c14a59dc.png">

**Comment by phpbits** [comment]
<img width="474" alt="screen shot 2019-02-05 at 1 34 33 am" src="https://user-images.githubusercontent.com/3365507/52225809-4236fd80-28e6-11e9-8721-393fb184d420.png">
