### ISSUE TITLE
Adding a new section within the Layout block generates a "Invalid Post Type" error

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#219]
Looks like it's trying to create a `block-coblocks` post_type from the URL parameter. 

![screenflow](https://user-images.githubusercontent.com/1813435/52225527-95726700-2878-11e9-9566-5412d6b9de87.gif)

**Comment by phpbits** [comment]
@richtabor Fixed the button link

**Comment by phpbits** [comment]
@richtabor closing this issue since we are removing the tab when empty. Thanks!
