### ISSUE TITLE
Tweak Layout block tab names/positions

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#221]
The only change from this screenshot is that "My Sections" should be the last tab:
<img width="993" alt="screenshot 2019-02-04 12 51 22" src="https://user-images.githubusercontent.com/1813435/52227019-69f17b80-287c-11e9-85cd-a5d6dc36ec97.png">

**Comment by richtabor** [comment]
Related: #222

**Comment by phpbits** [comment]
@richtabor My Sections tab is now positioned last 👍
