### ISSUE TITLE
Create "Disable Blocks" Settings inside the Editor

### ISSUE THREAD

**Issue by phpbits** [thatplugincompany/coblocks#228]
Let’s start thinking about this. A sidebar panel within Gutenberg, or maybe even a modal popup (like how Keyboard shortcuts come up). 

Purpose:
Be able to turn on/off any number of blocks within the editor. A control panel for blocks. 

I’m thinking of a grid of blocks where you click on a block to enable it or disable it. When disabled it fades a bit. 

Questions:
1. Would it be possible to turn off whole categories of blocks?

2. Would it be possible to do a filterable search for blocks via name, category and keywords?

Ideas:
Need to be able to filter all installed blocks. 

Could maybe use toggles (like the ToggleControl). 

Would be interesting to include some way for block descriptions to be used, maybe using a ToolTip or DropDown type component.

**Comment by phpbits** [comment]
@richtabor I'll be adding search and validation. Here's the preview of what it is now. You can change the UI if you have something better :)

![screen capture on 2019-02-06 at 12-42-57](https://user-images.githubusercontent.com/3365507/52320931-f7fc6c00-2a0c-11e9-91c8-e81a62fa90fd.gif)

**Comment by phpbits** [comment]
Here's the preview with live search option 💪💪💪
![screen capture on 2019-02-06 at 15-55-00](https://user-images.githubusercontent.com/3365507/52327627-bcbb6680-2a27-11e9-80b5-55faa167002b.gif)

**Comment by richtabor** [comment]
Wow, this is looking great! Is there a way to ensure the modal stays a min height - instead of having it change and reposition to the center while searching?

Also, let’s add our icon to the modal, just like we did for Layouts/Sections. 

Looking so nice!

**Comment by phpbits** [comment]
@richtabor Thanks! Yeah, those changes can be done via CSS. I'll take care of the validation first then adjust the UI :)

**Comment by phpbits** [comment]
@richtabor Added popover for validation. Not sure what's the best way to show the warning message. Let me know your thoughts. Thanks!
<img width="1165" alt="screen shot 2019-02-06 at 8 45 20 pm" src="https://user-images.githubusercontent.com/3365507/52342387-3e26ef00-2a50-11e9-92bf-d9a560a60651.png">
