### ISSUE TITLE
Focus block search field when opening the Block Manager

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#230]
That's the behavior on the inserter. Can we do the same? 
<img width="731" alt="screenshot 2019-02-06 15 17 16" src="https://user-images.githubusercontent.com/1813435/52370994-58e26f00-2a22-11e9-957d-32f8f425e23a.png">

**Comment by phpbits** [comment]
@richtabor added `autofocus` on the search field 👍

**Comment by richtabor** [comment]
Great!
