### ISSUE TITLE
"Disable all" toggles should be hidden when live searching blocks

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#231]
The results are filtered. It will likely confuse people on what action is being taken, if not all the available blocks within a category are viewable. So a solution would be to hide the toggle when results are filtered. 

<img width="719" alt="screenshot 2019-02-06 15 22 24" src="https://user-images.githubusercontent.com/1813435/52371298-1c634300-2a23-11e9-8002-c0087d938f62.png">

**Comment by phpbits** [comment]
@richtabor Added 👍
