### ISSUE TITLE
Block Manager "Disable all" toggles are not working

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#232]
The disable all toggles are not properly functioning. I don't believe they were working before I did the UI tweaks. 

By default, they should be turned off, with the label "Disable all". When clicked, the blocks within that category should be disabled. Users can then select individual blocks to re-enable from that category. 

One question thought, when a toggle is turned back off (to its initial state) should the blocks within that category be registered once again? I think so.

**Comment by phpbits** [comment]
@richtabor added : https://github.com/thatplugincompany/coblocks/commit/cf7e810b7faeed4297a8f87b4f40bc695b6796f9
