### ISSUE TITLE
Filter the word "Blocks" from the Common Blocks toggle label

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#235]
As we're using the category label within the Block Manager disable toggle, we need to filter out the duplicated "Blocks" word, if that word exists within the category (which is honestly shouldn't - but that's out of our control). 

<img width="592" alt="screen shot 2019-02-07 at 6 49 53 am" src="https://user-images.githubusercontent.com/1813435/52409887-ca630180-2aa4-11e9-9402-965699013c18.png">

**Comment by phpbits** [comment]
@richtabor done :)
