### ISSUE TITLE
Add a "No blocks found" notice if there are no filtered results

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#240]
Here's what happens currently: 
![screenflow](https://user-images.githubusercontent.com/1813435/52416511-c5f41400-2ab7-11e9-8f75-3970783d7e86.gif)

Here is what the block inserter does (which we should emulate): 
<img width="579" alt="screenshot 2019-02-07 09 08 18" src="https://user-images.githubusercontent.com/1813435/52416582-ede37780-2ab7-11e9-8c34-7d4385c68f63.png">

**Comment by phpbits** [comment]
@richtabor added :) just need better styling. Thanks!
