### ISSUE TITLE
Improve toggle behavior on Block Manager

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#242]
Toggling whole block categories is working great; there is just one tweak I think we need to implement. 

When you disable all the blocks within a category, then activate one of those, and then toggle off the "Disable all" toggle, you end up with the block you enabled now turned off (it should still be on). 

![screenflow](https://user-images.githubusercontent.com/1813435/52417191-49facb80-2ab9-11e9-89bf-eb42876a08d9.gif)

**Comment by phpbits** [comment]
@richtabor sorry about that, just fixed :)

**Comment by richtabor** [comment]
Works perfectly!
