### ISSUE TITLE
Improve labels of the Block Manager category toggles

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#243]
When a toggle is activated, the label currently displays "All {category.title} blocks disabled". I really like the relative label title that explains to the user what just happened. 

So now, users can then go in and toggle on various blocks within that category. 

The issue here is that when a block is enabled within a category, **all** of the blocks within the category are no longer disabled. So the label "All {category.title} blocks disabled" is no longer accurate.

**A potential solution:** 
Is it possible to change the label **only** if there are blocks within that category that are enabled? Say to "Enable all". 

<img width="747" alt="screenshot 2019-02-07 09 24 52" src="https://user-images.githubusercontent.com/1813435/52417609-4287f200-2aba-11e9-8a00-93cb000d4029.png">

**Comment by phpbits** [comment]
@richtabor Changed the label to "Enable All" instead. Let me know your thought. Thanks!
