### ISSUE TITLE
CoBlocks block foreground and background icon colors are not working in the Block Manager

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#245]
We're using the <BlockIcon> component, which can deploy block colors for the icons (if registered). Our blocks are not showing their custom icon color that we've defined, but other blocks are.

I installed another block plugin that uses colors and this is what you get:
![screenflow](https://user-images.githubusercontent.com/1813435/52432457-6eb26b80-2ad8-11e9-962d-1b28e5861a4a.gif)

**Comment by phpbits** [comment]
@richtabor added custom foreground color for icons :)

**Comment by phpbits** [comment]
@richtabor Just needed opacity change when disabled. Reopening. Thanks!

**Comment by richtabor** [comment]
Lookin' good. 🎉
