### ISSUE TITLE
Block Manager icons block list styling with 5.0

### ISSUE THREAD

**Issue by phpbits** [thatplugincompany/coblocks#248]
Install Gutenberg 5.0 then open Block Manager

<img width="583" alt="screen shot 2019-02-08 at 12 53 05 pm" src="https://user-images.githubusercontent.com/3365507/52459518-9c62e780-2ba0-11e9-8536-754f32855ef8.png">

**Comment by richtabor** [comment]
Looks like core's styling is now loading after ours.

**Comment by richtabor** [comment]
<img width="1044" alt="screen shot 2019-02-08 at 7 50 34 am" src="https://user-images.githubusercontent.com/1813435/52479323-3c574b80-2b76-11e9-9a19-7737280051be.png">
