### ISSUE TITLE
Feature Request: Custom link for Click to Tweet block

### ISSUE THREAD

**Issue by seb86** [thatplugincompany/coblocks#25]
Would like to apply a custom link using the **Click to Tweet** block.

My idea is that if the URL field is empty then it will link the current page as it does already now. If a URL is entered then the tweet will use that link instead.

Is this something you can do for the next release?

**Comment by richtabor** [comment]
That's an interesting idea. The one concern I have is that the expected behavior of a click to tweet element is to tweet a caption/link to the current page. I'm not sure if having it link elsewhere would be a great experience, as those tweeting the link would never really know what that link was - unless they clicked it themselves (from the tweet). 

Does that make sense?

**Comment by seb86** [comment]
I understand that a change my make things confusing. We can discuss UI ideas if that helps?

**Comment by richtabor** [comment]
Well I don't think it's a question of UI per se, but the expected behavior from the reader's perspective.

**Comment by seb86** [comment]
Oh no, I think I have confused you. The custom link is on the editors side. Not the front-end. For example, the button block allows you to enter or search a post to link to. I would like the same to override the link the tweet will post. The front-end will be the same.

**Comment by richtabor** [comment]
Right. What I'm saying that is if the link that is inserted into the tweet is not that page (but a custom link instead), then the end user does not know what that link is that they're tweeting.

**Comment by richtabor** [comment]
@seb86 Do you get where I'm thinking there?

**Comment by seb86** [comment]
When a user uses the button block and enters a link they know what it is so why would it be different here?

**Comment by richtabor** [comment]
Not that user, the person clicking the "Tweet" button.

**Comment by richtabor** [comment]
Actually, the whole idea of a Click to Tweet element is to tweet the text _with_ a reference link that points back to the source.

**Comment by seb86** [comment]
![image](https://user-images.githubusercontent.com/497406/51360553-6912c880-1acc-11e9-9866-070ea20c4226.png)

Twitter adds the reference link as part of the share when you post the tweet. So adding the reference link as part of the tweet to me would not work because then the user would be posting two links and not one.

**Comment by seb86** [comment]
`http://twitter.com/share?&text=Check%20out%20this%20board%20of%20%23Gutenberg%20block%20ideas.%20There%20are%20so%20many.%20Vote%20on%20which%20blocks%20should%20be%20built%20first.%20%23wpblocksuite&url=https://blocksuite.xyz/&via=block_suite`

**Comment by richtabor** [comment]
Right, I get your point — but I don’t think that’s a good idea, The whole purpose of the click to tweet element is that the text is tweeted, with a reference to the source of that text. 

Having a different link (other than the actual page/post where the click to tweet element is present) is borderline deceptive. The person tweeting that text/link will not know what link they’re tweeting then, unless they copy it from the tweet (or parameter) and paste it in their browser.

**Comment by seb86** [comment]
I see your point. I wouldn't want to deceive a user.

**Comment by richtabor** [comment]
Whew! I’m glad we’re on the same page now. :)

**Comment by seb86** [comment]
Me too.
