### ISSUE TITLE
Gutenberg 5.0 ResponsiveBaseControl and OrientationControl Fixes

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#254]
<img width="370" alt="screen shot 2019-02-08 at 9 07 11 am" src="https://user-images.githubusercontent.com/1813435/52483063-f5bb1e80-2b80-11e9-9ecd-155e0cb1ff68.png">

**Comment by phpbits** [comment]
@richtabor Is this fix acceptable? I've added `.components-panel__body` at the top

**Comment by richtabor** [comment]
Looking good. I have a few tweaks to push.
