### ISSUE TITLE
Last column on the row block needs to have it's margin bottom removed when stacked

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#47]
As long as stackedOnMobile is set to `true`, the last `.wp-block-coblocks-column` should have its margin removed — when the columns stack up on mobile.

Here's a gif: 
![screenflow](https://user-images.githubusercontent.com/1813435/51475186-a20e9f80-1d4f-11e9-8b5e-1d8a61447d39.gif)

**Comment by richtabor** [comment]
This is on the frontend. We still have responsive touch-ups to do within the editor #28 later on.

**Comment by phpbits** [comment]
@richtabor Added the fixes here : https://github.com/thatplugincompany/coblocks/commit/cbfca2645507b044d700c2292b40e9ca4f9c78cf
