### ISSUE TITLE
Add coBlocksSpacing support to a few core blocks

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#58]
I think it'd be wise to add it to blocks that have support for background colors (excerpt for paragraph blocks), and blocks that have fullwidth alignments.

Here's a list: 
- Image
- Gallery
- Spacer
- Cover

**Comment by phpbits** [comment]
@richtabor Added on this pull request : https://github.com/thatplugincompany/coblocks/pull/86 . Thanks!
