### ISSUE TITLE
Row gutter value should also be used as the mobile margin value

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#64]
Currently we're [hard coding](https://github.com/thatplugincompany/coblocks/blob/master/src/blocks/row/styles/style.scss#L39) the margin bottom of the `.wp-block-coblocks-column` when it should really be using the gutter value on mobile.

![screenflow](https://user-images.githubusercontent.com/1813435/51621752-2c4b3500-1f03-11e9-8385-cf0aa55d284d.gif)

**Comment by phpbits** [comment]
@richtabor Added the fixes for frontend ;) Editor to follow 👍

**Comment by richtabor** [comment]
@phpbits We’re you able to finish the frontend? Thanks!

**Comment by richtabor** [comment]
Looks good!
