### ISSUE TITLE
Inline padding is taking precedence over the dimensions control

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#74]
If you set an advanced padding, then save/view/edit the post again - that inline padding value overrides the dimensions control dropdown. 

![screenflow](https://user-images.githubusercontent.com/1813435/51637141-f6b94280-1f28-11e9-9009-c1ff3c96e40f.gif)

**Comment by richtabor** [comment]
Note that if you press "Reset" it reverts the control back to the non-advanced view (but the padding stays the same - as it's inline).

**Comment by phpbits** [comment]
@richtabor created PR. Thanks!
