### ISSUE TITLE
Add a drop zone to the Media Card block rendered image/video

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#75]
This way users can drag and drop in a new image to replace it, instead of removing and image first - then uploading/dragging in.

**Comment by richtabor** [comment]
I've started work on this on the [media-card-dropzone](https://github.com/thatplugincompany/coblocks/tree/media-card-dropzone) branch but couldn't quite figure it out. Mind giving it a look @phpbits?

**Comment by richtabor** [comment]
Figured it out. 🥳

Just need to work in a Spinner/loading effect now.

![screenflow](https://user-images.githubusercontent.com/1813435/51675741-92d36000-1fa2-11e9-8384-350b82a588df.gif)

**Comment by seb86** [comment]
> Just need to work in a Spinner/loading effect now.

@richtabor See what I did in my block for uploading with spinner. https://github.com/seb86/double-image

**Comment by richtabor** [comment]
![screenflow](https://user-images.githubusercontent.com/1813435/51677365-6706a900-1fa7-11e9-83e0-4229b358860e.gif)

**Comment by richtabor** [comment]
Thanks @

> > Just need to work in a Spinner/loading effect now.
> 
> @richtabor See what I did in my block for uploading with spinner. https://github.com/seb86/double-image

Thanks @seb86, looks good! I went with the core Spinner/is-transient approach.

**Comment by phpbits** [comment]
@richtabor Looks perfect 👍

**Comment by seb86** [comment]
@richtabor Cool
