### ISSUE TITLE
Add Icon Block

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#85]
## Spec for the Icon Block

I think it’d be a good idea to have an Icon block, where users can add an SVG icon to blocks (specifically our upcoming Feature block.  I’m thinking we could modify that block’s TEMPLATE to include the icon block in between the heading and paragraph blocks.

When we add the features + features block, can it add randomized icons? Instead of one default? Maybe on ComponentDidMount from within the Icon Block? It’d be a nice UX touch to have something like this. 

## Edit Function:
The block is really simple, just: div > div > SVG. A max width would be set either by utility class, or inline styling, on the div wrapping the SVG. 

We will have to make a custom control that also has an Advanced button (similar to the dimensions control) but when Advanced is clicked, reveals a RangeControl to fine-tune the icon size. These will be tied to the iconWidth attribute.  

Small, Medium, Large, Huge options for setting the max width of the icon. These add utility classes such as .has-small-icon and etc to the SVG block wrapper. If Advanced is enabled, and the user selects a range value, the utility classes should not be preset - and an inline style should match. 

## Block Toolbar
From the block toolbar users will be able to modify the icon selection. Users click the “Edit Icon” toolbar button and a popover appears above. The popover will have a search field up top (similar UI to the block inserter) and the available icons will be in a grid layout similar to that of the Styles previewed (but 3 columns wide). 

Clicking on an icon will replace the icon within the block - but the popover should remain open as users will likely try a couple icons first. 

Autocomplete should filter the icons based on keywords. For example, typing “food” may pull up the few food related icons we’ve built into the block. The icons will be available within the blocks icon.js file. For now we’ll just use text icons. Once the functionality is in place, Rich will identify icons to include and add relevant keywords for the searching feature. 

## Sidebar:
Users will need a URL input field s other can wrap the icon in a link. There should also be a toggle for having the link open up in another window. Color Settings will include a “Icon Color” palette setting, which controls the color of the icon.  The SVG should have a fill of currentColor, so that the color classes take effect for the fill. 

### Other thoughts: 
It should be hidden from the inserter with supports, inserter false. I don’t see a reason to let folks add it wherever really.

We should consider having a margin dimensions control, where the user can set top and bottom margin for the icon.  The left and right margin options should be disabled and the utility class should not apply margin left and right.

**Comment by richtabor** [comment]
Here’s what I’m thinking for the Icon Selector. It’s based on the same component framework of the typography panel. 

![a9f3dfa2-b1f8-4761-9218-9714e4000a5f](https://user-images.githubusercontent.com/1813435/51654237-e030dc80-1f64-11e9-8aee-44c2c625e825.png)

**Comment by richtabor** [comment]
We could use icons from [Material Design](https://material.io/tools/icons/?style=baseline).

**Comment by richtabor** [comment]
And perhaps we can use a core block style for "Outlined" and "Filled" designs?

**Comment by phpbits** [comment]
@richtabor having an issue with dropdown popover. Text inputs and textarea are not working, it closes the popover. I can't find why but select control and range control is working. Really weird.

**Comment by phpbits** [comment]
> And perhaps we can use a core block style for "Outlined" and "Filled" designs?

I'm actually thinking of content marketing icons :) but that's probably hard to create, material design icons looks great too!

**Comment by phpbits** [comment]
@richtabor autocomplete is having issues either, maybe we can do SelectControl for now? What do you think?

**Comment by richtabor** [comment]
> @richtabor autocomplete is having issues either, maybe we can do SelectControl for now? What do you think?

I think having them filterable, where users can type to search for icons, is pretty important. :/

**Comment by richtabor** [comment]
Here's the new UI for the icon search, now that we've moved to the block sidebar. ![icon-block-ui-2](https://user-images.githubusercontent.com/1813435/51919214-f8fc2080-23b0-11e9-805d-9c32b7b05136.jpg)

**Comment by phpbits** [comment]
Created and added more options. Here's the preview on how Icon Block work :

![screen capture on 2019-01-30 at 20-29-02](https://user-images.githubusercontent.com/3365507/51981369-ceec5080-24cd-11e9-9e95-93ba7db0df44.gif)

Would love to add the selection on toolbar but there are limitations on Gutenberg core as of the moment and decided to use Inspector Control instead.

**Comment by richtabor** [comment]
<img width="419" alt="screenshot 2019-01-31 07 38 44" src="https://user-images.githubusercontent.com/1813435/52054665-43a1a800-252b-11e9-9710-016a187ad266.png">
