### ISSUE TITLE
Improve text of the "No top spacing" and "No bottom spacing" ToggleControls

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/coblocks#93]
Lets use the following: 

Remove top spacing
Toggle to remove any margin applied to the top of this block.

Remove bottom spacing
Toggle to remove any margin applied to the bottom of this block.

The toggled on text is fine.

**Comment by phpbits** [comment]
@richtabor PR for fixes - https://github.com/thatplugincompany/coblocks/pull/110
